### ISSUE TITLE
Rebuild zitadel proto files

### ISSUE THREAD

**Issue by danielsf97** [caos/zitadel-go#80]
Hello, I would like to use this rpc method from zitadel:
`rpc AddPasswordlessRegistration(AddPasswordlessRegistrationRequest) returns (AddPasswordlessRegistrationResponse)`

However, it doesn't seem to be able by the management client. However the AddPasswordlessRegistrationRequest and AddPasswordlessRegistrationResponse messages are available.

Would it be possible to update the rpc compiled files as well?

Thanks in advance

**Comment by livio-a** [comment]
Hey @danielsf97 

The client is built every night with the newest protos. But i'll check what the problem might be.

**Comment by livio-a** [comment]
Hey @danielsf97 
The clients were indeed not built correctly, resp. copied from the Docker image. We just merged the fix.
Thanks again for the issue!

**Comment by danielsf97** [comment]
Thank you for the fix!
