### ISSUE TITLE
Providing json keys as string

### ISSUE THREAD

**Issue by danielsf97** [caos/zitadel-go#82]
Currently I find myself migrating from a rest to a grpc approach when using Zitadel.
In order to have a more flexible handling of keys for local development, one feature that would be of a major benefit, is the possibility to handle these keys by content instead of configuring them by path, like we currently have to do with `zitadel.WithKeyPath(keyPath)` when creating e.g. a new management client.
The idea would be to have something similar to the way we provide the credentials in the function `NewJWTProfileAssertion(userID, keyID string, audience []string, key []byte, opts ...AssertionOption) JWTProfileAssertionClaims`.

Thank you in advance

**Comment by livio-a** [comment]
Hey @danielsf97 

Tanks again for the feedback. This makes total sense.
I've just created a PR #83, which enables you to directly provide a JWT Profile Token Source on the client with one of the following possibilities:
https://github.com/caos/zitadel-go/blob/5da00410b691b325f5fb8494cf3476d96c57a374/pkg/client/middleware/auth.go#L27-L43

For example when still using the file directly:
```
client, err := management.NewClient(
	[]string{oidc.ScopeOpenID, zitadel.ScopeZitadelAPI()},
	zitadel.WithJWTProfileTokenSource(middleware.JWTProfileFromPath("key.json")),
)
```

Is this roughly how you imagined it?

**Comment by livio-a** [comment]
Hey @danielsf97 have you had time to check it out yet?
I could also create a prerelease of the PR if you'd like.

**Comment by danielsf97** [comment]
> Hey @danielsf97 have you had time to check it out yet? I could also create a prerelease of the PR if you'd like.

Sorry for the late reply, this looks exactly how I imagined it. Thanks a lot! A prerelease would be nice. Keep up the good work!

**Comment by livio-a** [comment]
> Sorry for the late reply, this looks exactly how I imagined it. Thanks a lot! A prerelease would be nice. Keep up the good work!

No problem and thanks for the great feedback! I've just created release v0.2.0-beta-1:
```
go get -u github.com/caos/zitadel-go@v0.2.0-beta.1
```

We'll merge the PR as soon as you confirm that it works for you.

**Comment by danielsf97** [comment]
I only had time to test it today. I am sorry for that. But, good news, it works flawlessly!! Nice work!
Thank you once again!

**Comment by livio-a** [comment]
Great! Let me know if you need anything else.
